apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- services.yml

images:
- name: goserver
  newName: eltoncmapos1/gitops
  newTag: 9377e403f53f25cc2d053da34fffe563df540f76
